class Medecine {
    constructor(id, name, type, desciption, productionDate, expDate) {
      this.id = id; // represents the id generated by the firestore
      this.name= name;
      this.type= type;
      this.desciption = desciption;
      this.productionDate = productionDate;
      this.expDate= expDate;
    }
  }
   
module.exports = Medecine;