
class Post {
    constructor(id, title, contenu,date, visibility,uid, uname, uphoto) {
      this.id = id; // represents the id generated by the firestore
      this.title = title;
      this.contenu = contenu;
      this.date = date;
      this.uid = uid; 
      this.uname = uname;
      this.uphoto = uphoto;
      this.visibility= visibility;
    }
  }
   
  module.exports = Post;