
class User {
    constructor(id, fullName, email) {
      this.id = id; // represents the id generated by the firestore
      this.fullName = fullName;
      this.email = email;
    }
  }
   
  module.exports = User;